#deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easydoggie
  template:
    metadata:
      labels:
        app: easydoggie
    spec:
      containers:
      - name: testapp
        image: easydoggie/testapp:latest
        ports:
        - containerPort: 80